Repository CS2103JAN2018-W10-B1/main, pull requests merged in 2018-04, with the labels that each got.

#127 Make comparison method for Name case insensitive; Remove unused method
  src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
Labels: priority.high, severity.medium, type.task

#126 Two new UI Panels
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.medium, type.task

#128 Ensure that transaction cannot be added if a payee is the payer
  src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
  src/main/java/seedu/address/logic/parser/AddTransactionCommandParser.java
  src/main/java/seedu/address/model/transaction/Transaction.java
Labels: priority.high, type.bug

#140 Allow transaction amount to be split by units and by percentages
  collated/functional/steven-jia.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteTransactionCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/main/java/seedu/address/logic/parser/AddTransactionCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/util/BalanceCalculationUtil.java
  src/main/java/seedu/address/logic/util/CalculationUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/DebtsList.java
  src/main/java/seedu/address/model/DebtsTable.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Balance.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/transaction/SplitMethod.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/transaction/TransactionType.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlAdaptedTransaction.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/TransactionCard.java
  src/main/resources/view/CreditorListCard.fxml
  src/main/resources/view/DebtorListCard.fxml
  src/test/data/XmlSerializableAddressBookTest/typicalTransactionsAddressBook.xml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoableCommandTest.java
  src/test/java/seedu/address/storage/XmlAdaptedTransactionTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TransactionBuilder.java
  src/test/java/seedu/address/testutil/TypicalTransactions.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.high, type.enhancement

#141 Update user guide and update person-related command names
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonsCommand.java
  src/main/java/seedu/address/logic/commands/SelectPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/SelectCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/ListPersonsCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SelectPersonCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/EditPersonCommandSystemTest.java
  src/test/java/systemtests/FindPersonCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectPersonCommandSystemTest.java
Labels: type.task

#142 Update collated code
  collated/functional/ongkc.md
  collated/functional/phmignot.md
  collated/functional/steven-jia.md
  collated/test/ongkc.md
  collated/test/phmignot.md
  collated/test/steven-jia.md
Labels: type.task

#143 PorteFolio & DvpGuid & UserGuide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/paulhenrimignot.adoc
Labels: type.task

#152 Edit person name
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/DebtsList.java
  src/main/java/seedu/address/model/DebtsTable.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/transaction/TransactionList.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
  src/test/java/systemtests/AddPersonCommandSystemTest.java
Labels: priority.high, severity.medium, status.ongoing, type.bug

#158 UI: Transaction List adaptive
  src/main/resources/view/TransactionListCard.fxml
  src/main/resources/view/TransactionListPanel.fxml
Labels: priority.medium, type.task

#174 Renaming the name of the Ui into SmartSplit, renaming the data storage
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.medium, severity.low, type.bug
