Repository CS2103JAN2018-W10-B1/main, pull requests merged in 2018-03, with the labels that each got.

#19 User Stories updated and reordered
  docs/DeveloperGuide.adoc
Labels: team

#20 Create transaction model
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/model/transaction/Transaction.java
Labels: enhancement, individual

#27 About Us
  docs/AboutUs.adoc
  docs/images/damithc.jpg
  docs/images/lejolly.jpg
  docs/images/ongkc.png
  docs/images/phmignot.png
  docs/images/steven-jia.png
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
Labels: individual

#32 Able to pass tests.
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TransactionListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/TransactionCardHandle.java
  src/test/java/guitests/guihandles/TransactionListPanelHandle.java
Labels: enhancement

#62 Tests for TransactionCard.
  src/main/java/seedu/address/ui/TransactionCard.java
  src/test/java/guitests/guihandles/TransactionCardHandle.java
  src/test/java/seedu/address/testutil/TransactionBuilder.java
  src/test/java/seedu/address/ui/TransactionCardTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: individual

#63 DeleteCommand
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteTransactionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTransactionCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/transaction/TransactionList.java
  src/main/java/seedu/address/model/transaction/exceptions/TransactionNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement, individual

#83 Browser panel removal
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.medium, type.task

#84 Select and Unselect a person, displays the related transactions
  src/main/java/seedu/address/commons/events/ui/PersonPanelNoSelectionEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/transaction/TransactionContainsPersonPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: priority.medium, type.enhancement

#89 Ensure formate of balance complies with regex
  src/main/java/seedu/address/logic/util/BalanceCalculationUtil.java
Labels: severity.medium

#101 Update show all person
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/transaction/Transaction.java
Labels: type.task

#102 Update person card Ui for Balance
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.task

#104 Debts table
  src/main/java/seedu/address/logic/util/BalanceCalculationUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/DebtsList.java
  src/main/java/seedu/address/model/DebtsTable.java
  src/main/java/seedu/address/model/person/Balance.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/transaction/Amount.java
  src/main/java/seedu/address/model/transaction/Transaction.java
Labels: priority.medium, type.task
